# Site settings
title: Laura McNerney
email: mcnerney14 [at] gmail [dot] com
description: > # this means to ignore newlines until "baseurl:"
  Hi!  I'm Laura!  I love learning new things and flying planes.  I'm putting up free resources on flying.  Please contact me if you need a good pilot.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lauramcnerney.com" # the base hostname & protocol for your site
#twitter_username:
github_username:  mcnerney14

# Build settings
markdown: kramdown
